name: made on water
favicon: null
layout_spectrum: 0
typography_spectrum: 0.05913978
title: made on water
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#396cb1'
    - '#7392be'
    - '#4a4f61'
    - '#b2cef1'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
