name: madeonwater
favicon: null
layout_spectrum: 0.23951
typography_spectrum: 0.03322
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: made on water
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FCFCFD'
    - '#040303'
    - '#4192D9'
    - '#76BEF2'
    - '#779AB4'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.188172
purpose: []
