typography_spectrum: 0
color:
  brandColors:
    - '#7a797e'
    - '#66676c'
    - '#8b8481'
    - '#96928b'
    - '#7e8f8f'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: made on water
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: 'http://www.madeonwater.com/about/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: made on water
description: more than just a sailing adventure
purpose: []
