name: made on water
favicon: null
layout_spectrum: 0
typography_spectrum: 0.18031
title: made on water
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7a797e'
    - '#66676c'
    - '#8b8481'
    - '#96928b'
    - '#7e8f8f'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
