layout_spectrum: 0.5376344
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3724829
  brandStrength: 0.8351254
  rhythmicContrast: 0.6200717
  brandColors:
    - '#FCFCFD'
    - '#040303'
    - '#4192D9'
    - '#76BEF2'
    - '#779AB4'
  lightness: 1
typography_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: madeonwater
